name: Test Manifest Builds

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use the Flox installer, even though we're running the flake, because
      # it gives us the correct Nix install.
      - name: "Install Flox"
        uses: "flox/install-flox-action@main"

      - name: "Set NIX_CONFIG experimental-features"
        run: echo "NIX_CONFIG=experimental-features = nix-command flakes" >> $GITHUB_ENV

      # Test against the `main` branch of `flox/flox` so that we can exercise
      # new fixes, features, and catch regressions.
      - name: "Set FLOXBIN env var"
        run: echo "FLOXBIN=nix run github:flox/flox --" >> $GITHUB_ENV

      - name: "Debug nix.conf"
        run: nix config show

      - name: "Enable build features"
        run: flox config --set-bool features.build true

      - name: "Show flox binary path"
        run: echo "Flox is at $FLOXBIN"

      - name: "Run flox version"
        run: $FLOXBIN --version

      - name: "Run make"
        run: make
